export function BlogData() {
    const dt = "Sun Apr 20 2025";
    return [
        { id: 1, link: "/blog/abc", title: "Boston's most advanced", image: '/temp/before-rm/image-1.png', date: dt, description: "In sint vero dolor. Et quaerat iste labore unde hic et temporibus. Et dolore occaecati commodi minima vero iure ad in. Doloremque sint rerum modi doloribus. Ipsa cupiditate consequatur velit et inventore explicabo. Voluptatem voluptatem ipsum consectetur magni sint voluptatem." },
        { id: 2, link: "/blog/abc", image: '/temp/before-rm/image-2.png', title: "Small Frozen Hat", date: dt, description: "Et voluptas doloremque nihil saepe. Voluptatum soluta aspernatur adipisci iure eum." },
        { id: 3, link: "/blog/abc", title: "New ABC 13 9370", image: '/temp/before-rm/image-3.png', date: dt, description: "Repellendus qui temporibus dolorum aut et in minus. Asperiores corporis illum quia voluptas fugit ullam nulla est maxime. Fuga neque doloremque neque voluptates earum est est nostrum sint. Voluptatem suscipit odit natus aspernatur aliquam fugiat nostrum rerum. Est unde voluptate nam ex pariatur quia asperiores quis." },
        { id: 4, link: "/blog/abc", image: '/images/image-4.png', date: dt, title: "Sleek Rubber Shirt", description: "Enim amet odio eligendi non sed doloribus magni facere. Eligendi animi repellat iure autem sunt. Magnam corporis laudantium iste possimus. Sit aut consequatur voluptatem commodi est quia quia ex aperiam." },
        { id: 5, link: "/blog/abc", title: "New ABC 13 9370", image: '/temp/before-rm/image-1.png', date: dt, description: "Aut sunt suscipit officia. Eveniet nostrum accusamus quod eaque. Quia et velit voluptatem voluptas ratione sit aut enim. Maiores voluptas ipsam delectus doloribus soluta dolores dignissimos atque omnis." },
        { id: 6, link: "/blog/abc", image: '/temp/before-rm/image-2.png', date: dt, title: "Handmade Rubber Tuna", description: "Ab rem consequuntur praesentium accusantium vero quis similique porro qui. Nemo omnis mollitia omnis itaque ullam aliquam ut labore reprehenderit. Aut aliquam dolores aut dignissimos ad. Ipsum fuga quia soluta non. Tenetur vitae necessitatibus saepe voluptas quasi rerum animi. Illo qui nobis non eligendi eveniet dolores." },
        { id: 7, link: "/blog/abc", title: "The automobile  consists", image: '/temp/before-rm/image-3.png', date: dt, description: "Id doloribus quia quisquam. Soluta odit error saepe ea laborum tempore sit consectetur. Minus rerum ut accusamus. Eos quia corrupti voluptates molestiae. Occaecati ipsa harum aliquid." },
        { id: 8, link: "/blog/abc", image: '/temp/before-rm/image-4.png', date: dt, title: "Licensed Rubber Chips", description: "Atque qui excepturi minus aut et a. Explicabo facilis quis aperiam earum voluptates unde rerum corporis. Officiis corporis vitae quam et nisi dolore id. Perferendis mollitia illo dolores." },
        { id: 5, link: "/blog/abc", title: "Carbonite web goalkeeper", image: '/temp/before-rm/image-1.png', date: dt, description: "Voluptas tempore tempora non aut rerum. Ea omnis eaque aut impedit possimus consectetur. Vel aliquam dolores amet voluptates voluptatem. Ut ut ullam neque unde quia quos sit." },
        { id: 6, link: "/blog/abc", image: '/temp/before-rm/image-2.png', date: dt, title: "Practical Metal Fish", description: "Ipsum eum libero dignissimos enim adipisci quos voluptas consequatur qui. Temporibus dolor exercitationem soluta sequi sint. Dolorem dolor et reprehenderit voluptas ipsum molestias." },
        { id: 7, link: "/blog/abc", title: "The Football Is Good For ", image: '/temp/before-rm/image-3.png', date: dt, description: "Expedita occaecati exercitationem. Adipisci non minus. Fugit aperiam error consequuntur commodi quibusdam iure. Molestias aut id aut temporibus. Perferendis aut voluptatem soluta neque in. Dolorum eaque enim quasi voluptas rerum odit laboriosam et et." },
        { id: 8, link: "/blog/abc", image: '/temp/before-rm/image-4.png', date: dt, title: "Handmade Steel Chips", description: "Saepe atque est. Ut et eum ea unde sit quia odit et. Magnam est eos et est fugiat et quis." },
    ]
}